### ISSUE TITLE
does not build

### ISSUE THREAD

**Issue by ithakaa** [QianheYu/headscale-panel-ui#2]
does not build even with

`export NODE_OPTIONS=--openssl-legacy-provider`

abandoning project due to lack of documentation

**Comment by QianheYu** [comment]
Since each developer using this project has a different environment and may encounter different problems when building, it is not possible to give coverage of all possible scenarios for the time being. Currently, I have not encountered any problems with debian, ubuntu, or macOS, and if I have, I can use the above commands to solve the problem. If you still can't solve the problem, please check your own environment first to see if there is any problem, and then seek other solutions.
